name: CKL_Studio_CI

on: 
    push:
        branches: ["master", "dev"]
    pull_request: 
        branches: ["master"]

jobs:
  sonarcloud:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Verify project structure
      run: |
        if (!(Test-Path "CKL_Studio.csproj")) { throw "CKL_Studio.csproj not found" }
        if (!(Test-Path "lib\CKLLib.dll")) { throw "CKLLib.dll not found in lib folder" }
        if (!(Test-Path "lib\CKLDrawing.dll")) { throw "CKLDrawing.dll not found in lib folder" }
        
        tree /f

    - name: Add DLL references (manual method)
      run: |
        $projContent = @"
        <Project Sdk="Microsoft.NET.Sdk">
            <ItemGroup>
            <Reference Include="CKLLib">
                <HintPath>lib\CKLLib.dll</HintPath>
            </Reference>
            <Reference Include="CKLDrawing">
                <HintPath>lib\CKLDrawing.dll</HintPath>
            </Reference>
            </ItemGroup>
        </Project>
        "@
        $projContent | Out-File -FilePath "CKL_Studio.csproj" -Append -Encoding utf8

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin /k:"CKL_Studio" /o:"yvunglord" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        dotnet build CKL_Studio.sln
        dotnet test --configuration Release --collect:"XPlat Code Coverage"
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"